export const RENDER_JOBDATA = 'RENDER_JOBDATA';
export const CURRENT_ROUTE = 'CURRENT_ROUTE';
export const COOK_DETAILS = 'COOK_DETAILS';
export const SEARCHING_RECIPE = 'SEARCHING_RECIPE';
export const SEARCHING_RECIPE_API = 'SEARCHING_RECIPE_API';
export const SEARCHING_RECIPE_API_FAILED = 'SEARCHING_RECIPE_API_FAILED';
export const SEARCHING_RECIPE_API_PENDING = 'SEARCHING_RECIPE_API_PENDING';
export const SIGNED_IN = 'SIGNED_IN'